name: Example CI

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello (23f2004759@ds.study.iitm.ac.in)
        run: echo "Hello from 23f2004759@ds.study.iitm.ac.in"
